service.singletons:
  - com.networknt.balance.LoadBalance:
      - com.networknt.balance.RoundRobinLoadBalance
  - com.networknt.cluster.Cluster:
      - com.networknt.cluster.LightCluster

server.serviceId: com.networknt.petstore-1.0.0
server.environment: dev-proxy
handler.basePath: /v1
